export enum OrderNormalStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PACKING = 'PACKING',
  DELIVERED = 'DELIVERED',
  DELIVERED_FAILED = 'DELIVERED_FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  DEBT = 'DEBT',
  DONE = 'DONE',
  PAID_FAIL = 'PAID_FAIL',
}

export enum OrderRepairStatus {
  WAITING_FOR_CONFIRM = 'WAITING_FOR_CONFIRM',
  RECEIVED = 'RECEIVED',
  DIAGNOSING = 'DIAGNOSING',
  QUOTING = 'QUOTING',
  REPAIRING = 'REPAIRING',
  COMPLETED = 'COMPLETED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  UNREPAIRABLE = 'UNREPAIRABLE',
}
