export enum OrderNormalStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PACKING = 'PACKING',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum OrderRepairStatus {
  WAITING_FOR_CONFIRM = 'WAITING_FOR_CONFIRM',
  RECEIVED = 'RECEIVED',
  DIAGNOSING = 'DIAGNOSING',
  QUOTING = 'QUOTING',
  REPAIRING = 'REPAIRING',
  COMPLETED = 'COMPLETED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  UNREPAIRABLE = 'UNREPAIRABLE',
}
