export enum PermissionSystem {
  // User permissions
  CREATE_USER = 'CREATE_USER',
  VIEW_USER = 'VIEW_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Product permissions
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  VIEW_PRODUCT = 'VIEW_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  // Category permissions
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  VIEW_CATEGORY = 'VIEW_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  // Brand permissions
  CREATE_BRAND = 'CREATE_BRAND',
  VIEW_BRAND = 'VIEW_BRAND',
  UPDATE_BRAND = 'UPDATE_BRAND',
  DELETE_BRAND = 'DELETE_BRAND',

  // Order permissions
  CREATE_ORDER = 'CREATE_ORDER',
  VIEW_ORDER = 'VIEW_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  // Additional / Testing permissions
  TEST = 'TEST',
  ALL = 'ALL',
}
