export enum PromotionImageType {
  MAIN_BANNER = 'MAIN_BANNER',
  SUB_BANNER = 'SUB_BANNER',
  LEFT_BANNER = 'LEFT_BANNER',
  RIGHT_BANNER = 'RIGHT_BANNER',
  TOP_BANNER = 'TOP_BANNER',
  BOTTOM_BANNER = 'BOTTOM_BANNER',
  FRAME_PROMOTION = 'FRAME_PROMOTION',
}
